input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "[@metadata][index]" => "opendaimon-logs" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
}
